const taskConstants = {
    CREATE_TASK_REQUEST: "CREATE_TASK_REQUEST",
    CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
    CREATE_TASK_FAILURE: "CREATE_TASK_FAILURE",
    GET_TASK_REQUEST: "GET_TASK_REQUEST",
    GET_TASK_SUCCESS: "GET_TASK_SUCCESS",
    GET_TASK_FAILURE: "GET_TASK_FAILURE",
    GET_ALL_TASKS_REQUEST: "GET_ALL_TASKS_REQUEST",
    GET_ALL_TASKS_SUCCESS: "GET_ALL_TASKS_SUCCESS",
    GET_ALL_TASKS_FAILURE: "GET_ALL_TASKS_FAILURE",
    UPDATE_TASK_REQUEST: "UPDATE_TASK_REQUEST",
    UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
    UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
    DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE"
};

export default taskConstants;