const userConstants = {
    CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILURE: "CREATE_USER_FAILURE",
    LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
    LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
    LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
    LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE",
    LOGOUT_ALL_REQUEST: "LOGOUT_ALL_REQUEST",
    LOGOUT_ALL_SUCCESS: "LOGOUT_ALL_SUCCESS",
    LOGOUT_ALL_FAILURE: "LOGOUT_ALL_FAILURE",
    GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
    GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
    GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
    UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
    DELETE_PROFILE_REQUEST: "DELETE_PROFILE_REQUEST",
    DELETE_PROFILE_SUCCESS: "DELETE_PROFILE_SUCCESS",
    DELETE_PROFILE_FAILURE: "DELETE_PROFILE_FAILURE"
};

export default userConstants;